server:
  port: 80
  servlet:
    context-path: /spring-session-web



spring:
 #  redis 配置
  redis:
    host: redis.host
    port: 6379
    database: 1
    password: 123456
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 1000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接超时时间（毫秒）
        timeout: 0